"""add home/away starter fk to games

Revision ID: 13dd3d327474
Revises: a2705277d4b3
Create Date: 2026-07-19 18:47:49.123085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13dd3d327474'
down_revision: Union[str, Sequence[str], None] = 'a2705277d4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('home_starter_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_starter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'players', ['home_starter_id'], ['id'])
    op.create_foreign_key(None, 'games', 'players', ['away_starter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'away_starter_id')
    op.drop_column('games', 'home_starter_id')
    # ### end Alembic commands ###
