"""add api_call_log table for rate limiting

Revision ID: 29184f606b52
Revises: 07f00763ff2f
Create Date: 2026-07-20 10:07:39.599675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29184f606b52'
down_revision: Union[str, Sequence[str], None] = '07f00763ff2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_call_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_name', sa.String(length=50), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_call_log_api_name'), 'api_call_log', ['api_name'], unique=False)
    op.create_index(op.f('ix_api_call_log_called_at'), 'api_call_log', ['called_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_call_log_called_at'), table_name='api_call_log')
    op.drop_index(op.f('ix_api_call_log_api_name'), table_name='api_call_log')
    op.drop_table('api_call_log')
    # ### end Alembic commands ###
