"""add first inning runs for nrfi labeling

Revision ID: 67b5661337d9
Revises: 13dd3d327474
Create Date: 2026-07-19 18:49:10.678824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b5661337d9'
down_revision: Union[str, Sequence[str], None] = '13dd3d327474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('first_inning_home_runs', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('first_inning_away_runs', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'first_inning_away_runs')
    op.drop_column('games', 'first_inning_home_runs')
    # ### end Alembic commands ###
