"""initial schema

Revision ID: 98dc1040f17b
Revises: 
Create Date: 2026-07-19 18:31:45.712433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98dc1040f17b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('file_path', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mlb_team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('league', sa.String(length=10), nullable=False),
    sa.Column('division', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_mlb_team_id'), 'teams', ['mlb_team_id'], unique=True)
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mlb_venue_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('surface_type', sa.String(length=30), nullable=True),
    sa.Column('roof_type', sa.String(length=30), nullable=True),
    sa.Column('park_factor_runs', sa.Float(), nullable=False),
    sa.Column('park_factor_hr', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_mlb_venue_id'), 'venues', ['mlb_venue_id'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mlb_game_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('is_doubleheader', sa.Boolean(), nullable=False),
    sa.Column('game_number_in_series', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mlb_game_id', name='uq_games_mlb_game_id')
    )
    op.create_index(op.f('ix_games_date'), 'games', ['date'], unique=False)
    op.create_index(op.f('ix_games_mlb_game_id'), 'games', ['mlb_game_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mlb_player_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.Column('bats', sa.String(length=1), nullable=True),
    sa.Column('throws', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_mlb_player_id'), 'players', ['mlb_player_id'], unique=True)
    op.create_table('batter_game_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('batting_order_position', sa.Integer(), nullable=True),
    sa.Column('at_bats', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('hr', sa.Integer(), nullable=True),
    sa.Column('bb', sa.Integer(), nullable=True),
    sa.Column('k', sa.Integer(), nullable=True),
    sa.Column('vs_pitcher_hand', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', name='uq_batter_game')
    )
    op.create_index(op.f('ix_batter_game_logs_game_id'), 'batter_game_logs', ['game_id'], unique=False)
    op.create_index(op.f('ix_batter_game_logs_player_id'), 'batter_game_logs', ['player_id'], unique=False)
    op.create_table('bullpen_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('pitcher_id', sa.Integer(), nullable=False),
    sa.Column('pitches_thrown', sa.Integer(), nullable=True),
    sa.Column('back_to_back_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['pitcher_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bullpen_usage_game_id'), 'bullpen_usage', ['game_id'], unique=False)
    op.create_index(op.f('ix_bullpen_usage_team_id'), 'bullpen_usage', ['team_id'], unique=False)
    op.create_table('lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('batting_order_position', sa.Integer(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'team_id', 'player_id', name='uq_lineup_slot')
    )
    op.create_index(op.f('ix_lineups_game_id'), 'lineups', ['game_id'], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('moneyline_home', sa.Integer(), nullable=True),
    sa.Column('moneyline_away', sa.Integer(), nullable=True),
    sa.Column('run_line', sa.Float(), nullable=True),
    sa.Column('run_line_odds', sa.Integer(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('over_odds', sa.Integer(), nullable=True),
    sa.Column('under_odds', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_snapshots_game_id'), 'odds_snapshots', ['game_id'], unique=False)
    op.create_table('pitcher_game_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('ip', sa.Float(), nullable=True),
    sa.Column('er', sa.Integer(), nullable=True),
    sa.Column('k', sa.Integer(), nullable=True),
    sa.Column('bb', sa.Integer(), nullable=True),
    sa.Column('h', sa.Integer(), nullable=True),
    sa.Column('hr', sa.Integer(), nullable=True),
    sa.Column('pitch_count', sa.Integer(), nullable=True),
    sa.Column('avg_velo', sa.Float(), nullable=True),
    sa.Column('days_rest', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', name='uq_pitcher_game')
    )
    op.create_index(op.f('ix_pitcher_game_logs_game_id'), 'pitcher_game_logs', ['game_id'], unique=False)
    op.create_index(op.f('ix_pitcher_game_logs_player_id'), 'pitcher_game_logs', ['player_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=True),
    sa.Column('predicted_probability', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_game_id'), 'predictions', ['game_id'], unique=False)
    op.create_table('umpires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('umpire_name', sa.String(length=100), nullable=False),
    sa.Column('home_plate', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_umpires_game_id'), 'umpires', ['game_id'], unique=False)
    op.create_table('weather_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('temp_f', sa.Float(), nullable=True),
    sa.Column('wind_speed_mph', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.String(length=10), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_snapshots_game_id'), 'weather_snapshots', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_snapshots_game_id'), table_name='weather_snapshots')
    op.drop_table('weather_snapshots')
    op.drop_index(op.f('ix_umpires_game_id'), table_name='umpires')
    op.drop_table('umpires')
    op.drop_index(op.f('ix_predictions_game_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_pitcher_game_logs_player_id'), table_name='pitcher_game_logs')
    op.drop_index(op.f('ix_pitcher_game_logs_game_id'), table_name='pitcher_game_logs')
    op.drop_table('pitcher_game_logs')
    op.drop_index(op.f('ix_odds_snapshots_game_id'), table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index(op.f('ix_lineups_game_id'), table_name='lineups')
    op.drop_table('lineups')
    op.drop_index(op.f('ix_bullpen_usage_team_id'), table_name='bullpen_usage')
    op.drop_index(op.f('ix_bullpen_usage_game_id'), table_name='bullpen_usage')
    op.drop_table('bullpen_usage')
    op.drop_index(op.f('ix_batter_game_logs_player_id'), table_name='batter_game_logs')
    op.drop_index(op.f('ix_batter_game_logs_game_id'), table_name='batter_game_logs')
    op.drop_table('batter_game_logs')
    op.drop_index(op.f('ix_players_mlb_player_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_games_mlb_game_id'), table_name='games')
    op.drop_index(op.f('ix_games_date'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_venues_mlb_venue_id'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_teams_mlb_team_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('model_registry')
    # ### end Alembic commands ###
